### PR TITLE
Move to null safety

### PR DESCRIPTION
**Pull request by Jupi007**
This PR make this nice library `null safety` compliant :)

### CODE REVIEW

**Comment by Jupi007** [comment]
@LolzDEV Can you review please :)

**Comment by LolzDEV** [comment]
> @LolzDEV Can you review please :)

Done ;) thx for the contribution!

**Comment by Jupi007** [comment]
You're welcome @LolzDEV 🙂

Can you publish a new release, please?
I want to use your library into a project (which need to be null safety).

**Comment by LolzDEV** [comment]
> You're welcome @LolzDEV 🙂
> 
> 
> 
> Can you publish a new release, please?
> 
> I want to use your library into a project (which need to be null safety).

I will in some hours

**Comment by LolzDEV** [comment]
@Jupi007 updated on pub.dev 😃

**Comment by Jupi007** [comment]
Thanks a lot :)

**Pull request merged**
